# -*- coding: utf-8 -*-
"""Day -8 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dz5EjAZ9o2MCeNui_Q6rvHY1KbO43n8l

# **STRING SLICING :-**
"""

a=" Harry potter and the godlet of fire "
print(a[0:6])

print(a[6:13])

print(a[ : 6])

print(a[-5: ])

a="0123456789"
print(a[: : 2])

print(a[ : 7:2])

print(a[ : : -1])

"""# **PROBLEM SOLVING :-**

- 1. Write a program to get fibonacci series up to 10 numbers's .
"""

a=0
b=1

print(a)
print(b)

for i in range (2,11):
  c=a+b
  a=b
  b=c
  print(c)

a=0
b=1
n=int(input("ENter your number : "))

if n==1:
  print(1)
else:

  print(a)
  print(b)

  for i in range (2,n):
    c=a+b
    a=b
    b=c
    print(c)

"""- 2. Write a program to check if a number is prime or not ."""

a=int(input("Enter your number :"))
if a<=1:
  print("It is not a prime number ")

else:
  for i in range(2,a):
    if a%i==0:
      print("It is not a prime number ")
      break
  else:
    print("It is a prime number ")

"""- 3. Write a program to find a parindrome of integer ."""

num=int(input("Enter your number :"))
temp=num
rev=0

while num>0:
  dig=num%10
  rev=rev*10+dig
  num=num//10

if temp==rev:
  print("It is a palindrome number ")
else:
  print("It is not a palindrome number")

num=int(input("Enter your number :"))
temp=num
rev=0

while num>0:
  dig=num%10
  rev=rev*10+dig
  num=num//10

if temp==rev:
  print("It is a palindrome number ")
else:
  print("It is not a palindrome number")

"""- 4. Write a program to create an area calculator ."""

print("******* AREA CALCULATOR *******")

while True:
  print(""" press 1 to get the area of square
  press 2 to get the area of rectangle
  press 3 to get the area of circul
  press 4 to get the area of triangle """)

  choice=int(input("Enter your choice between 1 - 4 :"))
  if choice==1:
      while True:
        side=float(input("Enter the side of square :"))
        area=side*side
        print("Area of square is :",area)
        repeat=input(" do you want to try agin with square  ? (yes/no) :")
        if repeat=="no":
          break

  elif choice==2:
      while True:
        length=float(input("Enter the length of rectangle :"))
        width=float(input("Enter the width of rectangle :"))
        area=length*width
        print("Area of rectangle is :",area)
        repeat=input(" do you want to try agin with rectangle  ? (yes/no) :")
        if repeat=="no":
          break

  elif choice==3:
      while True:
        radius=float(input("Enter the radius of circle :"))
        area=((22/7)*(radius**2))
        print("Area of circle is :",area)
        repeat=input(" do you want to try agin with circle  ? (yes/no) :")
        if repeat=="no":
          break

  elif choice==4:
      while True:
        base=float(input("Enter the base of triangle :"))
        height=float(input("Enter the height of triangle :"))
        area=(base*height)/2
        print("Area of triangle is :",area)
        repeat=input(" do you want to try agin with triangle  ? (yes/no) :")
        if repeat=="no":
          break

  repeate1=input(" do you want to try agin ? (yes/no) :")
  if repeate1=="no":
    break

"""# **2nd PROBLEM SOLVING :-**

A = "OOTD.YOLO.ASAP.BRB.GTG.OTW"
1. Write a program to separate the following string into coma(,)
separated values.
2. Write a program to sort strings alphabetically in python.
3. Write a program to remove a given character from a string.


  Z = "F.R.I.E.N.D.S."
4. Write a program to remove dot(.) from the following string.
5. Write a program to check the number of occurrence of a
substring in a string.
"""

a="OOTD.YOLO.ASAP.BRB.GTG.OTW"
b=a.split(".")
print(b)

a=input("Enter anything here :")
b=sorted(a)
print(b)

a="hello"
b=a.replace("e","")
print(b)

Z = "F.R.I.E.N.D.S."
b=Z.replace(".","")
print(b)

a=" my name is shivpal "
b=a.count("i")
print(b)

"""# **3rd PROBLEM SOLVING :-**

1. Take an input from a user as a string then, reverse it.
2. Write a program to check if a string contains only digits.
3. Write a program to check if a string is palindrome.
4. Write a program to find number of vowels in a string.
5. Write a program to check if every word in a string begins with a
capital letter.
"""

a=input("ENter your choice :")
print(a[ : : -1])

a=input(" Enter your choice :")
b=a.isdigit()
print(b)

a=input(" Enter your choice :")
b=a.isdigit()
print(b)

a=input(" Enter your choice :")
rev=a[ : : -1]
if a==rev:
  print("It is a palindrome")
else:
  print("It is not a palindrome")

a=input(" Enter your choice :")
rev=a[ : : -1]
if a==rev:
  print("It is a palindrome")
else:
  print("It is not a palindrome")

a=input(" Enter your choice :")
vowel=0
for i in a:
  if i in "aeiouAEIOU":
    vowel+=1
print(vowel)

a=input(" Enter your choice :")
print(a.istitle())

a=input(" Enter your choice :")
print(a.istitle())

