# -*- coding: utf-8 -*-
"""Day-9 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15B9iaMudnILHL7VgrkMeOPXPhr14023Q

# **LIST :-**

- List are the collection of orderd and mutable data .

    - List are written inside the squared brackets .([])
    - The value inside a list is saparated by coma (,)
    - Mutable means once created , they can be changed .
    - Multiple datatypes can be written inside a list .
"""

fruits=["apple","banana","orange","mango","greps"]
print(fruits)
print(type(fruits))

fruits=["apple","banana","orange","mango","greps",12,12.5]
print(fruits)
print(type(fruits))

"""SLICICNG LIST ⏭"""

fruits=["apple","banana","orange","mango","greps"]
print(fruits[2])

fruits=["apple","banana","orange","mango","greps"]
print(fruits[-2])

fruits=["apple","banana","orange","mango","greps"]
print(fruits[1:3])

fruits=["apple","banana","orange","mango","greps"]
print(fruits[ : 3])

fruits=["apple","banana","orange","mango","greps"]
print(fruits[1:])

fruits=["apple","banana","orange","mango","greps"]
print(fruits[1: :2])

fruits=["apple","banana","orange","mango","greps"]
print(fruits[ : : -1])

fruits=["apple","banana","orange","mango","greps"]
print(fruits[ -1:-5:-1])

"""LIST TRERATION ⏭

Iteration Using For Loop

Iteration Using For Loop with Range and Length function

Iteration Using While Loop

Using Short-Hand For Loop
"""

fruits=["apple","banana","orange","mango","greps"]
for i in fruits:
  print(i)

fruits=["apple","banana","orange","mango","greps"]
for i in range (len(fruits)):
  print(fruits[i])

i=0
while i<(len(fruits)):
  print(fruits[i])
  i+=1

[print(i) for i in fruits]

"""# **LIST FUNCTION :-**

 to find the length of a list

 to count an occurence of a particular element

 to add to the list

 to add to a specific location

to remove from a listto remove from a certain location
"""

fruits=["apple","banana","orange","mango","greps"]
print(fruits)

print(len(fruits))

fruits=["apple","banana","orange","mango","greps","apple"]
print(fruits.count("apple"))

fruits=["apple","banana","orange","mango","greps"]
fruits.append("kiwi")
print(fruits)

fruits=["apple","banana","orange","mango","greps"]
fruits.insert(2,"kiwi")
print(fruits)

fruits=["apple","banana","orange","mango","greps"]
fruits.pop(2)
print(fruits)

fruits=["apple","banana","orange","mango","greps"]
fruits.remove("banana")
print(fruits)



"""# LIST FUNCTION PART -2 :-

to create a copy of a list

to access an element

to entend the list

to reverse the list

to sort the list

to clear allthe data from the list
"""

fruits=["apple","banana","orange","mango","greps"]
b=[]
print(b)
b=fruits.copy()
print(b)

print(fruits.index("orange"))

c=["kiwi","pineapple"]
fruits.extend(c)
print(fruits)

fruits.reverse()
print(fruits)

fruits.sort()
print(fruits)

a=[1,5,6,8,9,5,22,5,95,5]
a.sort()
print(a)

a.clear()
print(a)

fruits.clear()
print(fruits)

"""# **LIST COMPREHENSION :-**

  
"""

a1=[30,40,50,60]
a2=[]

for i in a1 :
  a2.append(i)
print(a2)

a1=[30,40,50,60]
a2=[]

for i in a1 :
  if i>40:

    a2.append(i)
print(a1 ,"\n",a2)

a1=[30,40,50,60]
a2=[]

for i in a1 :
  if i>40:

    a2.append(i)
print(a1 ,"\n",a2)

a3=[i for i in a1]
print(a3)

a1=[30,40,50,60]
a2=[]

for i in a1 :
  if i>40:

    a2.append(i)
print(a1 ,"\n",a2)

a3=[i for i in a1 if i>40]
print(a3)

"""# **PROBLEM SOLVING :-**

A= ["Ross" , "Rachel" , "Monica" , "Joe"]
1. Write a program to swap first and forth element.
2. Write a program to add a new value at second position.
3. Write a program to delete a value from 3ra position.

B = [13, 7, 12, 10]
1. Write a program to multiply all the numbers in the list.
2. Write a program to get the largest number from the list.
"""

a= ["Ross" , "Rachel" , "Monica" , "Joe"]
a[0],a[3]=a[3],a[0]
print(a)

a.insert(1,"shiv")
print(a)

a.pop(3)
print(a)

mul=1
b = [13, 7, 12, 10]
for i in b:
  mul*=i
print(mul)

b = [13, 7, 12, 10]

# Arrange the list in ascending order

b.sort()
print(b)

print("The largest value in given list is : ", b[-1])
print("The smallest value in given list is : ", b[0])

