# -*- coding: utf-8 -*-
"""Day-10 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j64ba3jVKQi-FprMQZxw9K2Fje0lIIo

# **TUPLES :-**

Tuples are the collection of ordered and un-mutable data.

 -  For tuples no brackets are mandatory.

- By choice one can use parentheses.

-  The value inside a Tuple is separated by coma (,).

- Once created, tuples cannot be changed.

- Multiple datatypes can be written inside a tuples.
"""

a="mango","banana","kiwi"
print(type(a))

a=("mango","banana","kiwi")
print(type(a))

a="mango","banana","kiwi",6,1.5,12
print(type(a))

a=("shiv")
print(type(a))

a=("shiv",)
print(type(a))

"""# Slicing and Iteration in Tuples :-"""

a=("vivo","readmi","nokia","samsung","oneplus")
print(a[1:3])

print(a[ :3])

print(a[2: ])

print(a[ : : 2])

print(a[-1:-4:-1])

print(a[ : :-1])

print(a[-3:-6:-1])

"""WITH FOR LOOP"""

for i in a :
  print(i)

"""ALONG WITH RANGE AND LENGTH IN FOR LOOP"""

for i in range(len(a)) :
  print(a[i])

"""ALONG WITH WHILE LOOP"""

i=0
while i<len(a) :
  print(a[i])
  i+=1

"""# CORVERSION OF TUPLES AND TUPLE FUNCTIONS"""

a = ("OnePlus", "Nokia", "Redmi")
print ("before conversion", type (a)) # convert into list
a = list(a)

print ("after conversion", type(a))
a. append ("Vivo")
print (a)

a = tuple(a) # convert into tuple again
print ("after conversion", type(a))
print(a)

print(a.count("Vivo"))

print(a.index("Redmi"))

"""# PROBLEM SOLVING :-

1. Convert the following dictionary into JSON format.
Student_data = {"name": "David", "age":13, "marks" :87}
2. Access the value of age from the given data.
Student_data = {"name": "David", "age": 13, "marks" :87}
3. Pretty Print following JSON data.
Student_data = {"name": "David", "age": 13, "marks" :87}
4. Sort the following JSON keys and write them into a file.
Student_data = "name": "David", "age": 13, "marks":8
"""

import json
Student_data = {"name": "David", "age":13, "marks" :87}

print(type(Student_data))

data=json.dumps(Student_data)
print(data)

print(type(data))

Student_data = {"name": "David", "age": 13, "marks" :87}
# The 'Student_data' variable already contains the dictionary
# You can access it directly, instead of using json.load()
data = Student_data
print(data['age'])

import json
Student_data = {"name": "David", "age": 13, "marks" :87}

data = json.dumps(Student_data, indent=4, separators=(",", "="))

print(data)

Student_data = {"name": "David", "age": 13, "marks" :87}
f = open("demo.json", "w")
data = json.dumps(Student_data, indent=4, sort_keys=True)

f.write(data)

print("The data has been  added to the file . ")

