# -*- coding: utf-8 -*-
"""Day -12 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBLiO1kS3CbfeosOyw3pLDr0wawLRgUh

# **DICTIONARY :-**

  Dictionary allows user to write the data in the form of kry's and values .

  - Dictionary are enclosed inside curly brackets {}

  - Key's and value's are seperated by colon .(:)

  - Every key value pair is saparated by a coma (,)
"""

Employ_data = {"name":"shiv","age":19,"gender":"male"}
print(Employ_data)

print(Employ_data["name"])

"""ITERATION IN DICTIONARIES

Iteration in Dictionaries

Student={ "name": "John", "class": "6th", "roll_no" :23}

printing all the key names one by one

printing all the value names one by one

usina value function
"""

Student={ "name": "John", "class": "6th", "roll_no" :23}

for x in Student:
  print(x)

for y in Student:
  print(Student[y])

for x in Student.values():
  print(x)

for x,y in Student.items():
  print(x,y)

for x,y in Student.items():
  print(x,"=",y)

"""DICTIONARY FUNCTION PART (1)."""

Student={"name": "John", "class": "6th", "roll_no" :23}
#get
#item
#keys
#values
#сору

x=Student.get("name")
print(x)

a=Student.items()
print(a)

b=Student.keys()
print(b)

c=Student.values()
print(c)

d=Student.pop("name")
print(d)

d=Student.copy()
print(d)

"""DICTIONARY FUNCTION PART -2"""

Student={ "name": "John", "class" : "6th", "roll_no" :23}
#setdefault
#update
#pop
#popitem
#clear

a=Student.setdefault("name","shiv")
print(a)

print(Student)

a=Student.update({"name":"shiv"})
print(a)

print(Student)

a=Student.pop("name")
print(a)

print(Student)

a=Student.popitem()
print(a)

print(Student)

a=Student.clear()
print(a)

"""NESTED DICTIONARIES :"""

employ={1:{"Name":"Shiv","Age":19,"Gender":"Male"},
        2:{"Name":"Shivani","Age":19,"Gender":"Female"},
        3:{"Name":"Shivani","Age":19,"Gender":"Female"}}
print(employ)

employ={1:{"Name":"Shiv","Age":19,"Gender":"Male"},
        2:{"Name":"Shivani","Age":19,"Gender":"Female"},
        3:{"Name":"Shivani","Age":19,"Gender":"Female"}}
print(employ[2]["Age"])

employ={1:{"Name":"Shiv","Age":19,"Gender":"Male"},
        2:{"Name":"Shivani","Age":19,"Gender":"Female"},
        3:{"Name":"Shivani","Age":19,"Gender":"Female"}}
print(employ[1]["Name"])

print([1])

"""**PROBLEM SOLVING :-**

1. Write a python program to sort a dictionary by value.
2. Write a python script to print a dictionary where the keys are
numbers between 1 and 15 and the values are square of keys.
3. Write a program to multiply all the items in a dictionary.
4. Write a python program to sort a dictionary by key.
"""

a={"a":12,"b":14,"c":15,"d":91,"e":23}
a=sorted(a.values())
print(a)

a={}
for i in range (1,16):
  a[i]=i**2

print(a)

a={"a":1,"b":2,"c":3,"d":4,"e":5}
product=1
for i in a:
  product=product*a[i]
print(product)

a={12:"a",14:"b",15:"c",91:"d",23:"e"}
a=sorted(a.keys())
print(a)

