# -*- coding: utf-8 -*-
"""Day -7 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBBMLyrcogmCgTTbuFLocbZEEztlp2tc

# **STRING MANIPULATION :-**

- String are the combination of number , symbol and letter ,encbsed inside quatation .

- GRATING OF A STRING = String can be created by enclosing numbers , letters on special symbols inside double quatation .

- it means assigning a string value to a variables .
"""

a="hello shivpal singh "
print(a)

print(type(a))

"""LEN :-

  to find the length of the string .
"""

print(len(a))

"""COUNT :-

  to find the number of times a character  is occuring .
"""

print(a.count("e"))

"""LOWER :-

  to convert each letter to lower case .
"""

print(a.lower())

"""UPPER :-

  to convert each letter to upper case .
"""

print(a.upper())

"""INDEX :-

  to find the index of any character .
"""

print(a.index('e'))

"""FIND :-

  to find the  index number of a character .
"""

print(a.find("o"))

"""CAPITALIZE :-

  to convert the first letter to capital .
"""

print(a.capitalize())

"""TITLE :-

  to convert to all line in the title .
"""

print(a.title())

"""CASEFOLD :-

  to convert a string into lowecare
"""

print(a.casefold())

"""FORMATE :-

to write variables inside a string .
"""

b="my name is {} , my age is {}"
name="shivpal singh"
age=19
print(b.format(name,age))

"""CENTER :-

  it fills the given character's and centralizes a string .
"""

print(name.center(100))

print(name.center(100,"*"))

"""# **STRING FUNCTION :-**



  
"""

a ="hello"
b ="Hello123"
c="123456"
d ="HELLO"
e =" "
f ="Hello 123@"
g="1.234"

"""- 1. isalnum - Returns True if all characters in the string are alphanumeric"""

print(a,"=",a.isalnum())
print(b,"=",b.isalnum())
print(c,"=",c.isalnum())
print(d,"=",d.isalnum())
print(e,"=",e.isalnum())
print(f,"=",f.isalnum())

"""- 2. isalpha - Returns True if all characters in the string are in the alphabe"""

print(a,"=",a.isalpha())
print(b,"=",b.isalpha())
print(c,"=",c.isalpha())
print(d,"=",d.isalpha())
print(e,"=",e.isalpha())
print(f,"=",f.isalpha())

"""- 3. isdecimal - Returns True if all characters in the string are decimals"""

print(a,"=",a.isdecimal())
print(b,"=",b.isdecimal())
print(c,"=",c.isdecimal())
print(d,"=",d.isdecimal())
print(e,"=",e.isdecimal())
print(f,"=",f.isdecimal())

"""- 4. isdigit - Returns True if all characters in the string are digits"""

print(a,"=",a.isdigit())
print(b,"=",b.isdigit())
print(c,"=",c.isdigit())
print(d,"=",d.isdigit())
print(e,"=",e.isdigit())
print(f,"=",f.isdigit())

"""- 5. isnumeric - Returns True if all characters in the string are numeric."""

print(a,"=",a.isnumeric())
print(b,"=",b.isnumeric())
print(c,"=",c.isnumeric())
print(d,"=",d.isnumeric())
print(e,"=",e.isnumeric())

"""- 6. islower - Converts a string into lower case."""

print(a,"=",a.islower())
print(b,"=",b.islower())
print(c,"=",c.islower())
print(d,"=",d.islower())
print(e,"=",e.islower())

"""- 7. isupper - Returns True if all characters in the string are upper case"""

print(a,"=",a.isupper())
print(b,"=",b.isupper())
print(c,"=",c.isupper())
print(d,"=",d.isupper())
print(e,"=",e.isupper())

"""- 9. isspace - Returns True if all characters in the string are whitespaces."""

print(a,"=",a.isspace())
print(b,"=",b.isspace())
print(c,"=",c.isspace())
print(d,"=",d.isspace())
print(e,"=",e.isspace())

"""- 10. istitle - Returns True if the string follows the rules of a title."""

print(a,"=",a.istitle())
print(b,"=",b.istitle())
print(c,"=",c.istitle())
print(d,"=",d.istitle())
print(e,"=",e.istitle())

"""- 11. endwith - Return true if the string follows the rules of a title ."""

print(a,"=",a.endswith("o"))
print(b,"=",b.endswith("o"))
print(c,"=",c.endswith("o"))
print(d,"=",d.endswith("o"))
print(e,"=",e.endswith("o"))

"""- 12. startwith - Return true if the string starts with the specificed value ."""

print(a,"=",a.startswith("h"))
print(b,"=",b.startswith("h"))
print(c,"=",c.startswith("h"))
print(d,"=",d.startswith("h"))
print(e,"=",e.startswith("h"))

"""- 13. swapcase - swaps cases , lower case becomes upper case and vice versa."""

print(a,"=",a.swapcase())
print(b,"=",b.swapcase())
print(c,"=",c.swapcase())
print(d,"=",d.swapcase())
print(e,"=",e.swapcase())

"""- 14 . strip - Returns a trimed version of the string ."""

print(a,"=",a.strip("o"))
print(b,"=",b.strip("o"))
print(c,"=",c.strip("o"))
print(d,"=",d.strip("o"))
print(e,"=",e.strip("o"))

"""- 15. split - splits the string at the specified saparator and returns a list ."""

print(a,"=",a.split("o"))
print(b,"=",b.split("o"))
print(c,"=",c.split("o"))
print(d,"=",d.split("o"))
print(e,"=",e.split("o"))

"""- 16 . ljust - Return a left justified version of the string ."""

print(a,"=",a.ljust(10))
print(b,"=",b.ljust(10))
print(c,"=",c.ljust(10))
print(d,"=",d.ljust(10))

"""- 17. replace - Returns a string where a specified value is replaced with a specified value ."""

print(a,"=",a.replace("h","H"))
print(b,"=",b.replace("h","H"))
print(c,"=",c.replace("h","H"))
print(d,"=",d.replace("h","H"))

"""- 18. rindex - searching the string for a specified value and returns the last position of where it was found ."""

print(a,"=",a.rindex("o"))
print(b,"=",b.rindex("o"))

"""- 19. rfind - searching the string for a specified value and returns the last position of where it was found ."""

print(a,"=",a.rfind("o"))
print(b,"=",b.rfind("o"))
print(c,"=",c.rfind("o"))
print(d,"=",d.rfind("o"))

