# -*- coding: utf-8 -*-
"""Day -11 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jY94AWtF3sbiKfm8wRb5JEfjKX224OPz
"""

a=input("enter your item name")
if(a=="pizza"):
        print("your item is pizza and its prise is 300 rs")

for i in range (1,11   ,  2):
  print(i)

for i in range (1,7):
  print (i)

a= "sam"
for i in a :
  print(i , end = "  ")

##print separete word
print("good","morning")

##variables
age=20
print(type(age))

