# -*- coding: utf-8 -*-
"""day-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRBf6rtrtwifpUWZDZ_Rutlxsov9IgJS

# **Bonus Calculator**
"""

import pandas as pd

def calculate_bonus_and_export_to_excel():
    # User se input lena (sales amount in INR)
    total_sales = float(input("Enter the total sales amount in INR: "))

    # Bonus calculation
    bonus_1m = 0.001 * min(total_sales, 1_000_000)  # 0.1% of up to 1 million
    bonus_2m = 0.005 * max(0, min(total_sales - 1_000_000, 1_000_000))  # 0.5% of next 1 million
    bonus_3m = 0.01 * max(0, total_sales - 2_000_000)  # 0.2% of anything above 2 million

    # Total bonus
    total_bonus = bonus_1m + bonus_2m + bonus_3m

    # Data for Excel
    data = {
        "Milestone": ["1 Million", "2 Million", "3 Million", "Total"],
        "Bonus (INR)": [bonus_1m, bonus_2m, bonus_3m, total_bonus],
    }
    df = pd.DataFrame(data)

    # Export to Excel
    file_name = "bonus_calculation.xlsx"
    df.to_excel(file_name, index=False)

    print(f"\nThe bonus calculation has been saved to '{file_name}'!")
    print(df)

# Function call
calculate_bonus_and_export_to_excel()

import pandas as pd

def calculate_bonus_and_export_to_excel():
    # User se input lena (total sales amount in INR)
    total_sales = float(input("Enter the total sales amount in INR: "))

    # User se ek hi bonus percentage lena
    bonus_percentage = float(input("Enter the bonus percentage for total sales (%): ")) / 100

    # Bonus calculation
    total_bonus = bonus_percentage * total_sales

    # Data for Excel
    data = {
        "Milestone": ["Total Sales", "Total Bonus"],
        "Amount (INR)": [total_sales, total_bonus],
    }
    df = pd.DataFrame(data)

    # Export to Excel
    file_name = "total_bonus_calculation.xlsx"
    df.to_excel(file_name, index=False)

    print(f"\nThe bonus calculation has been saved to '{file_name}'!")
    print(df)

# Function call
calculate_bonus_and_export_to_excel()

"""=======================================================================================================

- 4. Nested if :-
A Nested if statement is one in which an if statement is nested inside another if statement .

   This is used when a variable must be processed more than once .

   Than nested if statement in python has the followning syntax .

                    if condition 1 :
                        Execute if condition 1 is true
                    if condition 2 :
                        Execute if condition is true
                        condition 2 ends here
                        condition 1 ends here
                    else :
                        Body of else
"""

precentage=float(input("Enter your percentage: "))
if precentage>=80:
    print("New phone")
    if precentage>=90:
        print("Go tript")
else:
  print("No phone,no trip")

"""- 6. Short Hand If Statement :-

    Short hand if statement is used when only one statement needs to be executed inside the if block .

    this statement can be mentioned in the same line which holds the if statement .

          if condition:
              if(condition):(body of if)
"""

marks=float(input("Enter your marks: "))
if marks>=33: print("Pass")

"""- 6. Short Hand If-else Statement :-
    
    It is used to mention if else statement in one line in which there is only one statement to execute in both if and else blocks , in simple words , if you have only one statement to execute one for if and one for else .

    you can put it all on the same line .
"""

marks=float(input("Enter your marks: "))
print("Pass") if marks>=33 else print("Fail")

"""# **PROBLEM SOLVING**

  1. Write a program to check if a number is positive ?
"""

number=float(input("Enter a number: "))
if number>0:
  print("Positive")
else:
  print("Negative")

"""2. Write a program to check whether a number is odd or  even ?"""

number=float(input("Enter a number: "))
if number%2==0:
  print("Even")
else:
  print("Odd")

"""3. Write a program to create whether the passed is a vowel or not ?"""

user=input("Enter a character: ")
if user=="a" or user=="e" or user=="i" or user=="o" or user=="u":
  print("Vowel")
else:
  print("Consonant")

"""4. Write a program to create area calculater ?"""

print("***** AREA CALCULATER *****")
print(""" Press 1 to get the area of square
press 2 to get the area of rectangle
press 3 to get the area of cirele
press 4 to get the area of of traingle""")

user=int(input("Enter your choice: "))
if user==1:
  side=float(input("Enter the side of square: "))
  area=side*side
  print("Area of square is: ",area)

if user==2:
    length=float(input("Enter the length of rectangle: "))
    breadth=float(input("Enter the breadth of rectangle: "))
    area=length*breadth
    print("Area of rectangle is: ",area)

if user==3:
    radius=float(input("Enter the radius of circle: "))
    area=3.14*radius*radius
    print("Area of circle is: ",area)

if user==4:
    base=float(input("Enter the base of traingle: "))
    height=float(input("Enter the height of traingle: "))
    area=0.5*base*height
    print("Area of traingle is: ",area)

else:
  print("Invalid choice")

"""5. Write a program to check if a number is a single number , 2 digit number and so on up to 5 digit ."""

user=input("Enter a number: ")
if len(user)==1:
  print("Single digit")
elif len(user)==2:
  print("Two digit")
elif len(user)==3:
  print("Three digit")
elif len(user)==4:
  print("Four digit")
elif len(user)==5:
  print("Five digit")
else:
  print("More than five digit")

