# -*- coding: utf-8 -*-
"""Day 3 ,py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aLRSWEee33XhV1ktDgp7mY6cwxsz7cO

# Problem Solving

1. Write a program to display a person name , age ans address in there diffrent lines .
"""

name = "shiv"
age = 19
address = "jaipur"
print(name)
print(age)
print(address)

name=input("enter your name :")
age=int(input("enter your age :"))
address=input("enter your address :")
print(name)
print(age)
print(address)

name = "shiv"
age = 19
address = "jaipur"
print(name,age,address,sep="\n")

"""2. Write a program to swap two variable ."""

x=25
y=35
x,y=y,x
print(x,y,sep="\n")

x=25
y=35
temp=x
x=y
y=temp
print(x,y,sep="\n")

"""3. Write a programm to convert a float into integer."""

a=float(input("enter your float number :"))
print(int(a))

"""4. Write a program to take details from a student for ID Card and then print it in different lines ."""

print(" STUDENT ID CARD ")
name=input("Enter your name:")
class1=int(input("Enter your class:"))
section=input("Enter your section:")
rollno=int(input("Enter your rollno:"))
print(name,class1,section,rollno,sep="\n")

"""5. Write a program to take an user input as integer than convert to float ."""

a=int(input("enter your integer number :"))
print(float(a))

"""# **CONDITIONAL STATEMENT :**

Conditional Statement allows computer to execute a cretain condition only if it is true .

Types of If condition :-
  
  - If the condition
  - If else condition
  - If elif else statement
  - Nested statement
  - Short hand if statement
  - Short hand if else statement

- 1. If the condtion :-
    
    the If statement is the most fundamental decision making  statement . The if statement in python has the subsequent syntax .

if(Experession):
                                                  statement(Body of if )
                                                print(Other)
"""

a=int(input("Enter your mobile number :"))
if a == 2565236552:
  print("your mobile number is correct")

print("Thank you ")

"""- 2. If else statement :-

  The if else statement is used when you want to give two conditions to the computer .
  
  Here if one condition is false . program executes the another condition .

if condition :
                        # will execute this block if the condition is true .
                      else:
                        # will executes this block if the condition is false .
"""

a=int(input("Enter your number :"))
if a>=50:
  print("Good")
else:
  print("Bad")

"""- 3. if elif else statement :-

  In this case the if condition is evaluted first .
  
  if it is flase the elif statement will be executed .

  if it also comes false then else statement will be executed .

  For multiple condition , more elif statement are added .

if condition :
                      Body of if
                  elif condition :
                      Body of elif
                  else :
                      Body of else
"""

a=int(input("Enter your number :"))
if a<=25:
  print("Bad")

elif a<=50:
  print("Good")

elif a<=75:
  print("Very Good")

else:
  print("Excellent")

"""- 4. Nested if :-

  A Nested if statement is one in which an if statement is nested inside another if statement .

  This is used when a variable must be processed more than once .

  Than nested if statement in python has the followning syntax .

if condition 1 :
                            Execute if condition 1 is true
                        if condition 2 :
                            Execute if condition is true
                            condition 2 ends here
                            condition 1 ends here
                        else :
                            Body of else
"""

