# -*- coding: utf-8 -*-
"""Day -10 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNt5DU5fMd2bLS5FsNWI5m9IrGtD-jrd
"""

# user ne ek string di .
# hame nikalna h us string me kitne time consenent h .
# ex. str. => abc cde bcae => b:3 ,c:3

# first of all vovels nikalna
data = " xyz abc def "
for char in data :
    print (char)

data = " xyz abc def "
for char in data :
    if char in "aeiou":
        print (char)

data = " xyz abc def "
for char in data :
    if char not in "aeiou":
      print (char)

# ab find out krna h ki consenent kitni baar aaye .
# hame key value formate me data chahiye .
mydictionary = {}
data = "xyz xyz"
for char in data :
    if char not in "aeiou":
      mydictionary[char]=1
print (mydictionary)

"x" in {'x': 1, 'y': 1, 'z': 1, ' ': 1}

"a" in {'x': 1, 'y': 1, 'z': 1, ' ': 1}

mydictionary = {}
data = "xyz xyz"
for char in data :
    if char not in "aeiou":
      if char not in mydictionary :
        mydictionary[char]=1
print (mydictionary)

if "x" in {'x': 1, 'y': 1, 'z': 1, ' ': 1}:
      print("hey")

dict1= {'x': 1, 'y': 1}
if "x" not in dict1 :
      dict1["x"]=25
print(dict1)

# yhn x ki value already thi to change nhi hua agar x ki jgh y , z , k hote to value change ho jati .

dict1= {'x': 1, 'y': 1}
if "y"  in dict1 :
      dict1["y"]=25
print(dict1)

dict1= {'x': 1, 'y': 1}
if "z"  not in dict1 :
      dict1["z"]=50
print(dict1)

dict1= {'x': 1, 'y': 1}
if "z"  not in dict1 :
      dict1["x"]+1
print(dict1)