# -*- coding: utf-8 -*-
"""youtube courses .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1pOCbBxRJLRr-C94d7BpLLVPEyO6-F-
"""

import os
import pandas as pd

# Data for the Excel file
data = {
    "Course": [
        "LINUX",
        "Git and GitHub",
        "C Language",
        "Python Language",
        "AWS",
        "Networking",
        "Spoken English",
        "Machine Learning",
        "Microsoft Excel",
        "Amazon Seller",
        "SQL",
        "Data Science",
        "Data Analytics",
        "Blogging",
        "Copywriting",
        "Ethical Hacking",
        "React JS",
        "Digital Marketing",
        "SEO",
        "Adobe",
        "Content Writing",
        "WordPress",
        "DSA",
        "Google Ads",
        "YouTube Marketing",
        "Google Analytics",
        "Landing Page Creation",
        "Front-End Development",
        "App Store Optimization",
        "Basic CSS",
        "Social Media Marketing",
        "Freelancing",
        "Adobe Photoshop",
        "Django",
        "Laravel",
        "R Programming",
        "Android Development",
        "Java",
        "MySQL",
        "MS Word",
        "Python NumPy",
        "Shopify",
        "Canva",
        "HTML",
        "Video Editing",
    ],
    "Links": [
        "https://www.youtube.com/watch?v=_tCY-c-sPZc, https://youtu.be/HsIS_DeDjQM, https://www.youtube.com/watch?v=l32UR9DcjLg",
        "https://youtu.be/Ez8F0nW6S-w, https://youtu.be/gwWKnnCMQ5c, https://youtube.com/playlist?list=PLu0W_9lII9agwhy658ZPA0MTStKUJTWPi",
        "https://youtu.be/irqbmMNs2Bo",
        "https://youtu.be/UrsmFxEIp5k, https://youtu.be/vLqTf2b6GZw, https://youtu.be/ERCMXc8x7mc",
        "https://youtu.be/FUcTTV8GQg8, https://youtu.be/V04FvpXSFS8, https://youtu.be/91JZG07lNY0",
        "https://www.youtube.com/live/jYjDYWY1Lak, https://youtu.be/vGjH9leVXaM",
        "https://youtube.com/playlist?list=PLAX41TUzaphDa3LtzzRZYWS5_MPUF0nz5",
        "https://youtu.be/LvC68w9JS4Y, https://youtu.be/O0Ka_nBRtN0",
        "https://youtube.com/playlist?list=PLXwTOG3-tRwgy4lJ9j_CPwpJmr2uCaGH1",
        "https://youtube.com/playlist?list=PLXwTOG3-tRwgLXmNkOvyzthahbcrevsfR",
        "https://youtu.be/2w-M4z7iQpk, https://youtu.be/MfqnESS-6p8",
        "https://youtu.be/2w-M4z7iQpk",
        "https://youtu.be/VaSjiJMrq24",
        "https://youtu.be/UweV0xywkWE",
        "https://youtu.be/vcQxkgHSPTc",
        "https://youtu.be/Rgvzt0D8bR4",
        "https://youtu.be/ZaC6oCIpjR0, https://youtu.be/ygsrt33azpk",
        "https://youtu.be/G6DmDqYLWL8",
        "https://youtu.be/CjxQTvq_kRo, https://youtu.be/aFrQMR7-p9s",
        "https://youtu.be/VQAwe1zT8D8",
        "https://youtu.be/J2h0Xb0WNwQ",
        "https://youtu.be/cpde11lI7_pE",
        "https://youtu.be/hCrO_cR7kno",
        "https://youtu.be/FuOmpoZjZ2s",
        "https://youtu.be/57SDj9nuVmc",
        "https://youtu.be/tO6b66gfQdY",
        "https://youtu.be/Cj69XLJmm7I",
        "https://youtu.be/Eu7G0jV0ImY, https://youtu.be/kUJPZbUPqro",
        "https://youtu.be/RQqxO--gZOs",
        "https://youtu.be/ywBg3YV2PJU, https://youtu.be/zg_mmC8THqM",
        "https://youtu.be/G_bVngx529Y",
        "https://youtu.be/4rZ0HvmoWUo, https://youtu.be/IvlaCyFmJWk",
        "https://youtu.be/qvQie2QP5Vg",
        "https://youtu.be/6tdfhlIoxOw",
        "https://youtu.be/xIApzP4mWyA",
        "https://youtu.be/NDto4BVHz4s",
        "https://youtu.be/-5oI_5ZwFS0, https://youtu.be/u64gyCdqawU",
        "https://youtu.be/Kdz9J5vC4_o",
        "https://youtu.be/KKgN_w71x3E",
        "https://youtu.be/5jAgNWO11e_g",
        "https://youtu.be/-TYSM0CDA4c",
        "https://youtu.be/Io3OniSMKoU",
        "https://youtu.be/yWJp7gQqCQ8",
        "https://youtu.be/0fGJyy8Of1A, https://youtu.be/QnK9QWkDiF8, https://youtu.be/bQ-HTp-tx40",
        "https://youtu.be/hAMkGN2zdaY",
    ],
}

# Create a DataFrame
df = pd.DataFrame(data)

# Save to Excel file
file_path = "/Downloads/Courses_and_YouTube_Links.xlsx"

# Create the directory if it doesn't exist
os.makedirs(os.path.dirname(file_path), exist_ok=True)

df.to_excel(file_path, index=False, sheet_name="Courses and Links")

file_path

